services:
  - type: web
    name: manage-rent-home
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DJANGO_SETTINGS_MODULE
        value: manage_rent_home.settings
      - key: ALLOWED_HOSTS
        value: .onrender.com
      - key: DEBUG
        value: False
